### ISSUE TITLE
Not able to deploy sample app via Render

### ISSUE THREAD

**Issue by kirtan** [stripe-samples/issuing-treasury#342]
# Bug report

"No render.yaml found on main branch." Error message on Render.com deploy page

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Followed "Deploy to a shareable web link" here: https://docs.stripe.com/baas/start-integration/sample-app?use-or-copy-sample-app=copy-sample-app&copy-sample-app-tabs=no-code-deployment

## Screenshots

<img width="1319" alt="Screenshot 2024-04-24 at 8 40 04 PM" src="https://github.com/stripe-samples/issuing-treasury/assets/271440/d3cec78f-dca4-432c-9bd0-2062be5d5bd5">

**Comment by snasir-stripe** [comment]
Hi @kirtan. Thank you for reporting this bug and sorry about the trouble. I've merged a fix that appears to be working for me after I tested it. Do you mind giving it another shot?

**Comment by kirtan** [comment]
Works now, thanks!
